# This is a basic workflow to help you get started with Actions

name: install-yarn

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - env:
          TEST_BASE64_FILE: ${{ secrets.TEST_BASE64_FILE }}
        run: |
          echo $TEST_BASE64_FILE | base64 --decode > file.txt
      - run: |
          echo `cat file.txt`
